-- ═══════════════════════════════════════════════════════════
-- EduTwin — Supabase Postgres schema
-- Run this once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- ═══════════════════════════════════════════════════════════

-- ── students ──────────────────────────────────────────────
-- One row per student. Replaces the metadata columns of enhanced_students_dataset.csv.
-- "generated by default" (not "always") so the one-off migration script can
-- insert explicit legacy student_ids from the old CSV; new sign-ups still
-- get an auto-assigned id. migrate_to_supabase.py resets the sequence after
-- the bulk insert so future inserts don't collide with migrated ids.
create table if not exists public.students (
  id           bigint generated by default as identity primary key,
  name         text not null,
  year         int not null default 1,
  branch       text not null default 'CSE',
  archetype    text not null default 'unknown',
  auth_user_id uuid references auth.users(id) on delete set null,
  created_at   timestamptz not null default now()
);

create unique index if not exists students_auth_user_id_key
  on public.students (auth_user_id)
  where auth_user_id is not null;

-- ── student_topics ────────────────────────────────────────
-- One row per (student, topic). Replaces the long-format topic rows of the CSV.
create table if not exists public.student_topics (
  student_id  bigint not null references public.students(id) on delete cascade,
  topic       text not null,
  score       double precision not null default 0.50,
  time_spent  double precision not null default 60.0,
  attempts    double precision not null default 2.0,
  confidence  double precision not null default 0.50,
  engagement  double precision not null default 0.50,
  fatigue     double precision not null default 0.30,
  updated_at  timestamptz not null default now(),
  primary key (student_id, topic)
);

-- ── student_memory ────────────────────────────────────────
-- Append-only profile snapshot history. Replaces student_memory.json.
-- The most recent row per student_id is the "cached" Live Learner Profile.
create table if not exists public.student_memory (
  id         bigint generated always as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  profile    jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists student_memory_student_id_created_at_idx
  on public.student_memory (student_id, created_at desc);

-- ── user_profiles ─────────────────────────────────────────
-- Links a Supabase Auth user to an app role and (for students) their student row.
create table if not exists public.user_profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  role       text not null check (role in ('teacher', 'student')),
  student_id bigint references public.students(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ═══════════════════════════════════════════════════════════
-- Row Level Security
-- The FastAPI server talks to these tables using the service_role key,
-- which bypasses RLS entirely — all real authorization happens in FastAPI
-- (see auth.py). RLS here is defense-in-depth: it blocks the anon/authenticated
-- keys (used client-side only for Supabase Auth) from reading/writing table
-- data directly, since the client never queries these tables itself.
-- ═══════════════════════════════════════════════════════════
alter table public.students        enable row level security;
alter table public.student_topics  enable row level security;
alter table public.student_memory  enable row level security;
alter table public.user_profiles   enable row level security;

-- No policies are created — default-deny for anon/authenticated roles.
-- service_role (used by the server) always bypasses RLS.
